export enum ActionTypes {
  SET_PAGE_NO = "SET_PAGE_NO",
  SET_FILTERS = "SET_FILTERS",
  SELECT_FILTERS = "SELECT_FILTERS",
  SET_CURRENT_ROWS = "SET_CURRENT_ROWS",
  SET_SEARCH_ACCESSORS = "SET_SEARCH_ACCESSORS",
  SET_SEARCH = "SET_SEARCH",
  SET_NO_OF_ROWS = "SET_NO_OF_ROWS",
  UPDATE_PROPS = "UPDATE_PROPS",
  SET_SELECTED_ROWS = "SET_SELECTED_ROWS",
  UPDATE_RESULTS = "UPDATE_RESULTS",
  SET_STYLESHEET = "SET_STYLESHEET",
}
