export const initialState = {
  columns: [],
  current: [],
  original: [],
  uniqueDataField: "",
  numberOfRows: 25,
  pageNumber: 1,
  minEntryIndex: 0,
  maxEntryIndex: 24,
  usePagination: false,
  filters: {},
  search: "",
  searchPlaceholder: "Search here...",
  selectedFilter: { filter: "default", option: "default" },
  filteredResults: {},
  searchAccessors: [],
  searchResults: {},
  canSelectRows: false,
  selectAll: false,
  selectedRows: {},
  results: {},
};
