import { TStyleVariables } from "../interafaces/units";

export const styleVariables: TStyleVariables = {
  "font-family": "Arial, Helvetica, sans-serif",
  "table-container-border": "#BBBFCA",
  "header-bg": "#dee1e9",
  "header-column-separator": "#ffffffd6",
  "even-row-bg": "#F4F4F2",
  "odd-row-bg": "#FFF",
  "row-hover": "#E8E8E8",
  "body-column-separator": "#bbbfcad6",
  "scrollbar-track-bg": "#ededed",
  "scrollbar-thumb-bg": "#c9c9c9",
  "header-color": "#323B4B",
  "header-font-size": "16px",
  "header-font-weight": "600",
  "body-font-color": "#323c47",
  "body-font-size": "15px",
  "body-font-weight": "500",
  "select-container-border": "#c6c6c6",
  "dropdown-arrow-color": "#cecece",
  "disabled-select-container": "#f0f0f0",
  "options-container-bg": "#fff",
  "options-container-border": "1px solid #f2f2f2",
  "options-container-box-shadow": "1px 1px 2px #d2d2d2",
  "selected-option-color": "#323B4B",
  "options-color": "#323c47",
  "options-font-size": "16px",
  "option-separator": "#d2d2d2",
  "option-hover": "#f3f3f3",
  "selected-option-bg": "#e6e6e6",
  "search-border": "2px solid #c6c6c6",
  "search-font-size": "16px",
  "search-font-color": "#323c47",
  "search-font-weight": "500",
  "pagination-text-color": "#323c47",
  "pagiantion-text-size": "15px",
  "pagination-text-weight": "500",
  "pagination-page-info-color": "#323B4B",
  "pagiantion-page-info-size": "15px",
  "pagination-page-info-weight": "500",
  "head-row-height": "45px",
  "body-row-height": "40px",
  "max-table-height": "100%",
  "cell-content-vertical-alignment": "middle",
  "empty-cell-height": "50px",
};
